### ISSUE TITLE
Incorrect 'workflow' link to RSV dataset on nextclade.org 

### ISSUE THREAD

**Issue by ammaraziz** [nextstrain/nextclade_data#171]
Hi guys,

The RSV workflow link on nextclade.org does not exit. It should be:

https://github.com/nextstrain/nextclade_data/tree/master/data/nextstrain/rsv/a/EPI_ISL_412866

Also in the above link the readme link is similarly incorrect!

This is for both RSVA and RSVB. 

<img width="652" alt="image" src="https://github.com/nextstrain/nextclade_data/assets/7768245/fa0cecbb-37e2-4a7d-a768-10472c78a1db">

**Comment by ivan-aksamentov** [comment]
Hi Ammar,

Thanks for the report! The idea was to provide a link to the source code of the Nextstrain workflow which produces the Nextclade dataset files you linked. This is useful for people who want to know how the dataset was produced, run it themselves or even to make their own customized version (e.g. to produce a custom Nextclade dataset).

It's here actually: https://github.com/nextstrain/rsv

We'll discuss internally how to better organize this and will fix the links.

**Comment by rneher** [comment]
Thanks, Ammar. I changed these links in the upstream repo to just point to the repo.

https://github.com/nextstrain/rsv/commit/28e7f8e4f065941636b5291855f1cdc7067fed99

With the next dataset release, these should fixed.

**Comment by ammaraziz** [comment]
@ivan-aksamentov Oh! Apologies should have paid more attention. I agree the link to the workflow that generates the data is super useful.

Glad it was at least useful!
