### ISSUE TITLE
New flu_h3n2_ha nextclade data module does not have EPI accessions

### ISSUE THREAD

**Issue by nhassell** [nextstrain/nextclade_data#181]
The newest released flu_h3n2_ha nextclade [dataset](https://github.com/nextstrain/nextclade_data/tree/master/data_output/nextstrain/flu/h3n2/ha/EPI1857216/2024-02-22--16-12-03Z) does not have EPI accessions listed within the tree.json file. This information was really helpful for downstream purposes. Could this information be added back? It is currently present in every other flu build.

**Comment by rneher** [comment]
thanks for flagging this. This must have been lost with the update to J clades (I had removed EPIs as coloring because it seemed useless, but it must have had this undesired side effect)

**Comment by rneher** [comment]
should be back with the next update.

**Comment by nhassell** [comment]
Thanks @rneher, much appreciated!
