### ISSUE TITLE
Latest flu_h1n1_na module is missing NA subclade "B"

### ISSUE THREAD

**Issue by uee9** [nextstrain/nextclade_data#187]
Hi There, 

The nextclade tree and training set for H1N1pdm09 NA set appears to be missing [subclade B](https://nextstrain.org/flu/seasonal/h1n1pdm/na/6y?c=subclade&label=Subclade:B), which circulated from ~2018-2020. The current tree available on the [online version](https://clades.nextstrain.org/tree) goes from A.1.1 directly into B.1.

![image](https://github.com/nextstrain/nextclade_data/assets/118827134/a70d06d1-2557-48b5-a29b-4f477be898b8)

Overall, this is a relatively minor issue but I suspect the exclusion of B in the training set is a bug. Thanks.

**Comment by rneher** [comment]
thanks a lot for flagging this. we'll update the dataset soon!

**Comment by rneher** [comment]
should be fixed once https://github.com/nextstrain/nextclade_data/pull/191 is released.

**Comment by uee9** [comment]
Thanks, Cc-ing Norman here so he’s aware.

Best,
Matt

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
