### ISSUE TITLE
Next update for sars-cov-2 (and nextstrain/sars-cov-2/wuhan-hu-1/proteins) dataset?

### ISSUE THREAD

**Issue by icestorm972** [nextstrain/nextclade_data#188]
Hi,

as the last update is ~54 days old (2024-02-16) and since then pango-designation released v1.26 (with all these "FLirT" and other sublineages of JN.1 👀), updated datasets for sars-cov-2* in nextclade would be nice to have? 🙃

CC @corneliusroemer

Best wishes and thanks
David

**Comment by ivan-aksamentov** [comment]
Hi @icestorm972,

Cornelius just [released](https://github.com/nextstrain/nextclade_data/releases/tag/2024-04-15--15-08-22Z) the new SC2 datasets, includding the `nextstrain/sars-cov-2/wuhan-hu-1/proteins`. They are already available on https://clades.nextstrain.org and in Nextclade CLI. Please check them out! Open a new issue if there's still remaining questions.
