### ISSUE TITLE
Difference between sars-cov-2-no-recomb and sars-cov-2

### ISSUE THREAD

**Issue by gbbio** [nextstrain/nextclade_data#32]
Hello,

I noticed that there is a difference between sars-cov-2-no-recomb and sars-cov-2 for example genome sequence ON609102.1 (https://www.ncbi.nlm.nih.gov/nuccore/ON609102.1?report=fasta). With dataset sars-cov-2 it classifies as 22C and with dataset sars-cov-2-no-recomb is classifies as 21L. I can provide more sequences if needed.

This may not necessarily be a bug. Maybe it is because sars-cov-2-no-recomb is outdated. Are there plans to update this dataset?

**Comment by corneliusroemer** [comment]
Hi @gbbio thanks for opening this issue.

You're entirely right, the `sars-cov-2-no-recomb` is outdated, less maintained as you can for example see by the date.

April vs July
<img width="734" alt="image" src="https://user-images.githubusercontent.com/25161793/179979250-13b67d14-95f2-4d60-82a6-aad265900df4.png">

<img width="704" alt="image" src="https://user-images.githubusercontent.com/25161793/179979257-792ee082-3c55-4aaa-a97b-645a04f36570.png">

What do you use it for? Creation of the no-recomb dataset is specifically for recombination hunting, and maybe also for reliable classification of low-coverage, e.g. Spike only sequences.

If there's demand for the dataset we can keep it more up to date. So thanks for raising this! Quick comment on your use case would be helpful.

**Comment by gbbio** [comment]
I use it for spike only sequences. Although the classification is not always correct I currently do not have a proper dataset to test this. For example clade 22B classifies 100% incorrect with sars-cov-2-no-recomb and spike only. I test this by first classifying genomes, then extract spike, and classify spike.

**Comment by corneliusroemer** [comment]
Yes, that's indeed the right dataset to use in this case and yes it will struggle to find the correct lineage as Spike is only ~10% of whole genome so much less information.

I'll try to update next time. Which countries are producing spike only? I've seen a few sequences from Brazil like that but overall not that much. Maybe they don't end up on GISAID though, so could be that there's a lot of people doing this internally for quick genotyping. Where are you based?

**Comment by gbbio** [comment]
It is an internal project and mostly done because of budgets. I think for now I got my answer, the sars-cov-2 is the main and most maintained dataset.

**Comment by corneliusroemer** [comment]
I will start keeping no-recomb at same release schedule moving forward so you can start using that from the next release onwards again. Thanks for sharing your use case!

**Comment by gbbio** [comment]
Thanks for that, that is highly appreciated. It is still possible that spike is not good enough but then at least I can test it.

**Comment by corneliusroemer** [comment]
Yes, Spike will not allow super fine grained placement but it's better than with recombinants and better than nothing.

We're thinking about adding some metric of placement uncertainty - like equally parsimonious placements similar to Usher, or even distance to next most parsimonious placement if there are no other equally parsimonious ones.
