### ISSUE TITLE
Leading space in attributes column of latest SARS-CoV-2 gene map prevents parsing by gffutils

### ISSUE THREAD

**Issue by huddlej** [nextstrain/nextclade_data#33]
### Current Behavior

The attributes column of [the latest SARS-CoV-2 gene map](https://github.com/nextstrain/nextclade_data/blob/master/data/datasets/sars-cov-2/references/MN908947/versions/2022-07-12T12:00:00Z/files/genemap.gff#L5) has an unexpected leading space before the gene name definitions. This space causes the default parsing of the key/value pairs in the column to fail with default parsing by gffutils. For example, the first line of the body gets parsed as:

```
.	.	gene	26245	26472	.	+	.	 gene_name%3DE
```

### Expected behavior

The first line of the body should be:

```
.	.	gene	26245	26472	.	+	.	gene_name=E
```

### How to reproduce
Steps to reproduce the current behavior:

```
$ curl -O https://raw.githubusercontent.com/nextstrain/nextclade_data/master/data/datasets/sars-cov-2/references/MN908947/versions/2022-07-12T12%3A00%3A00Z/files/genemap.gff
$ cat -vet genemap.gff
# Gene map (genome annotation) of SARS-CoV-2 in GFF format.$
# For gene map purpses we only need some of the columns. We substitute unused values with "." as per GFF spec.$
# See GFF format reference at https://www.ensembl.org/info/website/upload/gff.html$
# seqname^Isource^Ifeature^Istart^Iend^Iscore^Istrand^Iframe^Iattribute$
.^I.^Igene^I26245^I26472^I.^I+^I.^I gene_name=E$
.^I.^Igene^I26523^I27191^I.^I+^I.^I gene_name=M$
.^I.^Igene^I28274^I29533^I.^I+^I.^I gene_name=N$
.^I.^Igene^I266^I13468^I.^I+^I.^I gene_name=ORF1a$
.^I.^Igene^I13468^I21555^I.^I+^I.^I gene_name=ORF1b$
.^I.^Igene^I25393^I26220^I.^I+^I.^I gene_name=ORF3a$
.^I.^Igene^I27202^I27387^I.^I+^I.^I gene_name=ORF6$
.^I.^Igene^I27394^I27759^I.^I+^I.^I gene_name=ORF7a$
.^I.^Igene^I27756^I27887^I.^I+^I.^I gene_name=ORF7b$
.^I.^Igene^I27894^I28259^I.^I+^I.^I gene_name=ORF8$
.^I.^Igene^I28284^I28577^I.^I+^I.^I gene_name=ORF9b$
.^I.^Igene^I21563^I25384^I.^I+^I.^I gene_name=S$
```

See spaces between the final tab (`^I`) and the `gene_name`.

In contrast, here is the corresponding output for the flu H3N2 HA gene map:

```
$ curl -O https://raw.githubusercontent.com/nextstrain/nextclade_data/master/data/datasets/flu_h3n2_ha/references/CY163680/versions/2022-06-08T12%3A00%3A00Z/files/genemap.gff
$ ##gff-version 3$
##sequence-region CY163680.1 1 1737$
CY163680.1^Ifeature^Igene^I18^I65^I.^I+^I.^Igene_name=SigPep$
CY163680.1^Ifeature^Igene^I66^I1052^I.^I+^I.^Igene_name=HA1$
CY163680.1^Ifeature^Igene^I1053^I1715^I.^I+^I.^Igene_name=HA2$
```

### Possible solution

Create a new version of the SARS-CoV-2 data without these leading spaces.

(While we're at it, we could also specify the sequence id in the first column and GFF version in the first line, to match other GFF files in this repo, but that could be a separate PR.)

**Comment by corneliusroemer** [comment]
Thanks @huddlej for noticing. 

I've addressed this in the workflow repo but I still need to make sure this ends up correctly in the releases since I usually just copy the files from one version to the next and replace changed files, e.g. tree.json

So I'll leave this open for now.

**Comment by corneliusroemer** [comment]
Resolved in the latest release
