### ISSUE TITLE
Rename header for MPXV dataset

### ISSUE THREAD

**Issue by erinyoung** [nextstrain/nextclade_data#35]
### Context
I like using nextalign locally, but when I use nextalign with the MPXV dataset, and I keep the reference, the reference is listed as 'ref_in_coord' instead of a useful name. 

### Description
Please change the header for the reference fasta for MPXV dataset (https://github.com/nextstrain/nextclade_data/blob/master/data/datasets/MPXV/references/ancestral/versions/2022-08-09T12:00:00Z/files/reference.fasta)

### Examples
The header of https://github.com/nextstrain/nextclade_data/blob/master/data/datasets/MPXV/references/ancestral/versions/2022-08-09T12:00:00Z/files/reference.fasta is '>ref_in_coord Reference sequence in coord.fasta coordinates'

### Possible solution
Instead of '>ref_in_coord Reference sequence in coord.fasta coordinates', perhaps... '>AncestralMPX_ref' or an accession number.

**Comment by corneliusroemer** [comment]
Very reasonable request, I'll do it for the next release! Sorry for the bad name.

**Comment by corneliusroemer** [comment]
Closed in new release! Thanks for your suggestion @erinyoung
