### ISSUE TITLE
ENH: Add key RBD mutations as labelled mutations

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextclade_data#43]

**Comment by ktmeaton** [comment]
This would help a lot for downstream analytics! I'm calculating key RBD mutations after running nextclade [from this yaml](https://github.com/nextstrain/ncov/blob/master/defaults/rbd_levels.yaml). But my implementation in python is super slow (and not multi-threaded).

**Comment by corneliusroemer** [comment]
@ktmeaton  Hmm, I don't think this would do what you want since only private mutations that are labelled would get highlighted.

If you want to calculate key RBD mutations fast, the best way may be to:
a) select only the aaSubstitution column from the nextclade.tsv using tsv-select (from eBay's tsv-utils)
b) Then parse that - if you need it to be super fast a little Rust script could help.

**Comment by ktmeaton** [comment]
Ah, that makes sense, thanks for clarifying! I've been meaning to get more into rust, so I'll take a look.

**Comment by corneliusroemer** [comment]
This looks like a perfect task to get started in Rust
a) read in a config file, read in the mutation file
b) process mutations
c) output count

**Comment by corneliusroemer** [comment]
Probably obsolete
