### ISSUE TITLE
ENH: G_clade GB1 for RSV-B?

### ISSUE THREAD

**Issue by AngieHinrichs** [nextstrain/nextclade_data#61]
Thank you for adding datasets for RSV-A and RSV-B!  I am updating my scripts to use nextclade instead of scraping clade assignments from nextstrain.org.  There is a GB1 branch on nextstrain.org: https://nextstrain.org/rsv/b/genome?label=clade:GB1  However, nextclade did not assign G_clade GB1 to any of the expected sequences (e.g. KU316116, MG642053) and it looks like the rsv_b tree.json has no samples with G_clade = GB1.  

Any chance of adding GB1 samples and labels to rsv_b in a future release?

**Comment by corneliusroemer** [comment]
Good question how this came about. I wasn't closely involved with the RSV datasets, so I'm not sure how sequences were chosen for inclusion. G1 is the oldest clade so maybe it didn't make the cut, G1 doesn't seem to have a G clade name.

Let's see what @LauraU123 or @rneher say

G1 is definitely not in the tree, so cannot be assigned:

<img width="2264" alt="image" src="https://user-images.githubusercontent.com/25161793/214453227-61431b27-8f12-4832-999c-cfeab95ad3fa.png">

Here are G and whole genome clades:

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/25161793/214453320-033958da-f192-4036-b213-5b0ff02db0e5.png">

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/25161793/214453324-e564a6f2-2be4-4bd4-9a9e-ecd0b5594170.png">

Note that G1 is grey in the whole genome clade coloring.

**Comment by AngieHinrichs** [comment]
Thanks @corneliusroemer!  

For comparing current nextclade assignments with usher-tree-based assignments after labeling the tree using a combination of nextclade assignments with other sources, here is a tree of INSDC RSV-B sequences, built by usher using NC_001781.1 (= AF013254) as reference/root (because it's a RefSeq and that is more convenient in the UCSC Genome Browser framework), on which 5 types of clade assignment can be used for coloring:

* Goya clades assigned by nextclade (no GB1): https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/rsvB.2023-01-26.json?branchLabel=none&c=goya_nextclade
* Goya clades assigned by usher using a combination of nextclade and nextstrain.org assignments (no GB7 because there is only one GB7 sequence and `matUtils annotate` labels internal branches only): https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/rsvB.2023-01-26.json?branchLabel=none
* Ramaekers clades assigned by nextclade (no B3): https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/rsvB.2023-01-26.json?branchLabel=none&c=ramaekers_nextclade
* Ramaekers clades assigned by usher using a combination of nextclade and Table S1 from Supplementary Info of Ramaekers et al (B3 applied at root, so too broadly assigned): https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/rsvB.2023-01-26.json?branchLabel=none&c=ramaekers_usher
* Only the assignments from Ramaekers et al. Table S1 (for RSV-B, this explicitly includes some sequences marked 'no genotype'): https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/rsvB.2023-01-26.json?branchLabel=none&c=ramaekers_tableS1

**Comment by rneher** [comment]
Great to see you are also working on RSV, Angie. We should include more older sequences into the nextclade tree. We were hoping that there would soon be a more consolidated and continuously updated nomenclature -- but I haven't heard much in a while.

**Comment by AngieHinrichs** [comment]
I see GB1 is included now, thanks!
