### ISSUE TITLE
Some influenza datasets are missing glyco data (virus_properties.json)

### ISSUE THREAD

**Issue by ammaraziz** [nextstrain/nextclade_data#63]
### Context
The new influenza datasets include `virus_properties.json` which defines potential glycosylation sites. 

### Description
The `virus_properties.json` is only in the "new" datasets (those datasets with a more recent reference). The `virus_properties.json` should be very similar or identical between references.

For example, for h1n1_ha (CY121680) dataset has no glyc information:
https://github.com/nextstrain/nextclade_data/blob/5d7f1e06fd1c95acd52753f07a9ce4b2872e1e56/data/datasets/flu_h1n1pdm_ha/references/CY121680/versions/2023-01-27T12:00:00Z/files/virus_properties.json

But h1n1_ha (MW626062) has:
https://github.com/nextstrain/nextclade_data/blob/5d7f1e06fd1c95acd52753f07a9ce4b2872e1e56/data/datasets/flu_h1n1pdm_ha/references/MW626062/versions/2023-01-27T12:00:00Z/files/virus_properties.json

Would it be possible to include glycosylation for the 'older' references?

In addition, the vic_ha KX058884 (B/Brisbane/60/2008) is missing data in the `virus_properties.json` (the `vic_na` dataset has info on glyco sites)

**Comment by rneher** [comment]
I'll add them in the next release!

**Comment by rneher** [comment]
fixed in b55e22a595d561cf35aecef9bac5bc0c0f543da5
