### ISSUE TITLE
No datasets found having attributes name: flu_h1n1pdm_na 

### ISSUE THREAD

**Issue by mattdmem** [nextstrain/nextclade_data#69]
### Current Behavior
Dataset not got

`nextclade dataset get --name flu_h1n1pdm_na --output-dir nextclade_datasets/flu_h1n1pdm_na`

### Expected behavior
Expected it to get the dataset

### How to reproduce
Run the above command

### Possible solution
(optional)

### Your environment: if running Nextstrain locally
nextclade 2.11.0

### Additional context

This dataset is listed when using `nextclade dataset list`

<img width="1655" alt="Screenshot 2023-03-27 at 16 47 33" src="https://user-images.githubusercontent.com/16154750/227993875-087896a3-9b27-4ab1-b85b-e161d2f3761e.png">

**Comment by ivan-aksamentov** [comment]
The [fix](https://github.com/nextstrain/nextclade_data/pull/70) is released in Nextclade data version 2023-03-28 and deployed to production.

On my side, I verified that this command
```
nextclade dataset get --name flu_h1n1pdm_na --output-dir nextclade_datasets/flu_h1n1pdm_na
```
now correctly downloads the `flu_h1n1pdm_na` dataset.

Don't hesitate to comment or open a new issue if the problem persists.
